import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { VisualEditing } from "next-sanity"
import { SanityLive } from '@/sanity/lib/live';
import { draftMode } from 'next/headers';
import type { ReactNode } from 'react';
import { DisableDraftMode } from "@/components/DisableDraftMode";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const { isEnabled } = await draftMode();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <main style={{ flex: 1 }}>{children}</main>
        <SanityLive />
        {isEnabled && <VisualEditing />}
        {isEnabled && <DisableDraftMode />}
      </body>
    </html>
  );
} 